Dynamic Landing Pages
chingu-voyages/v52-tier3-team-38 pull request #32
Opened 2024-11-29 20:05 UTC by RossaMania

# Description
This pull request focuses on enhancing role-based navigation and improving clarity across components by renaming, restructuring, and simplifying pages. The changes are aimed at improving the maintainability and readability of the codebase while ensuring consistent user experiences for guests, admins, and users.

## Related to the following Jira/Trello issue 
- Landing Page

## Main changes explained:
- Add new component:
- - Created GuestHome component by adding a dedicated file at the root and migrating the landing page content.

- Rename components for clarity:
- - Renamed Home to GuestHome for better alignment with its purpose as a guest landing page.
- - Renamed Admin and User profile pages to ensure consistency and clarity in component naming.

- Refactor existing components:
- - Simplified the structure of the GuestHome component by removing unnecessary styles, resulting in cleaner and more efficient code.
- - Updated the Root component to handle user roles more effectively, improving role-based rendering logic.

## How to test:
1. check into Ross/feature/dynamic-landing-pages branch
2. do `npm install` and `npm run dev` to run this PR locally.
3. The landing page should load based on login! 
- If not logged in, should be the normal landing page! 
- If logged in as regular user, it should show regular user profile page! 
- If logged in as admin, it should show admin profile page!

## Screenshots or videos of changes:

![Screenshot 2024-11-28 214705](https://github.com/user-attachments/assets/be1aa209-a1f8-4797-8892-62549f64cc09)
![Screenshot 2024-11-28 214753](https://github.com/user-attachments/assets/51a2d7fb-b8ef-4535-b5a3-e978d5aac282)
![Screenshot 2024-11-28 214825](https://github.com/user-attachments/assets/984d41a2-6022-487c-b87e-13e0c7fd63d7)
![image](https://github.com/user-attachments/assets/6c0bd093-7526-45ea-ad67-7bfc67eb0252)
![image](https://github.com/user-attachments/assets/bf005835-6e26-451e-b9f4-670d49e09dfc)

2024-11-29 20:24 UTC, garysmith1933 commented on src/app/admin/[_id]/profile/page.js
Appointment requests being on the profile page of an admin is a little confusing.

2024-11-29 20:30 UTC, garysmith1933 commented on src/app/user/[_id]/profile/page.js
> +<h3>Here is a list of your installation requests:</h3>
I know this is a placeholder but having it shown twice on top of either like this just makes it look a bug.

2024-11-29 20:31 UTC, garysmith1933 requested changes
I added some comments but the big error here is that the correct landing page is not displayed when logging out as either a resident or an admin.  It will only revert back to the guest landing page after refreshing the page.

2024-11-30 01:03 UTC, RossaMania commented on src/app/admin/[_id]/profile/page.js
I agree!

All I'm trying to do at this point is hard code some data to meet the Acceptance Criteria laid out in the Trello Card.
![image](https://github.com/user-attachments/assets/a19967d7-c609-40b6-be7e-a6df49ee27b4)

The UserPage and AdminPage components should be as simple as possible with links to the other pages in the app.

I feel like your page on the "/private" route is actually a great start!

I feel like it will also help to get more stuff in Bootstrap Card components as well!

2024-11-30 02:06 UTC, RossaMania commented
> I added some comments but the big error here is that the correct landing page is not displayed when logging out as either a resident or an admin. It will only revert back to the guest landing page after refreshing the page. 

Yup! I have been working on that for the last hour! I think it's about to become a thing.

I was going to try to roll it into some routing and make a pull request... 

"Oh hey. I'll fix this log out thing, and while I do that, I can fix a couple routing issues at the same time, and then make a clean pull request titled something cute like 'Some route issues fixed!'"

But I think this log out stuff might need it's own pull request.

2024-11-30 02:37 UTC, garysmith1933 approved these changes

2024-11-30 03:05 UTC, merged